### ISSUE TITLE
Selectively pack..?

### ISSUE THREAD

**Issue by lurkio** [ZornsLemma/basictool#2]
Is it currently possible to choose which of the ABE's Pack options to enable and which to disable? (I believe there are six options in total.)

If not, I wonder if it would be worth adding such a feature, with commandline flags? (Maybe -p on its own would enable all Pack options, whereas -pR would enable only the removal of REMs. And -pRC would enable only REM-removal and concatenation? Etc.)

**Comment by ZornsLemma** [comment]
Hi lurkio,

I think these options (which you can see in --help) should do what you want:
```
  --pack-rems-n        answer N to "REMs?" question when packing
  --pack-spaces-n      answer N to "Spaces?" question when packing
  --pack-comments-n    answer N to "Comments?" question when packing
  --pack-variables-n   answer N to "Variables?" question when packing
  --pack-singles-n     answer N to "Use unused singles?" question when packing
  --pack-concatenate-n answer N to "Concatenate?" question when packing
```
I could implement something a bit like you suggest, although probably not quite that because I'd like to fit in with the way the argument parsing library I'm using works. It would have to be something like "--pack-options=X" where X would be "RC" or whatever. The reason I didn't do it like this is it felt a bit hard to list all the "R means blah, C means blah" stuff in the standard --help format, but I'm not averse to tweaking this if you feel strongly about it.

I'm also open to suggestions for renaming these options, provided it doesn't break the formatting of the help. :-) I originally started off with options like "--pack-keep-comments" instead of "--pack-comments-n" but they got a bit long by the time I got onto the "unused singles" option. I did want to give them all a common "--pack" prefix to keep things a little bit organised, if you see what I mean.

Cheers.

Steve

**Comment by lurkio** [comment]
Ah, no, that's fine. I was lazy and didn't read the help properly! I didn't realise these options were already available. Everything's fine as is. Thank you.

**Comment by ZornsLemma** [comment]
Great, thanks. The offer's still there to tweak the options when you've had some more experience and worn your fingers down to a stub typing those names out. :-)

But I'll close this issue for now and you can always re-open it later.
